pip3 install --no-dependencies /tmp/packages/zipp-3.7.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/traitlets-5.1.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pyrsistent-0.18.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/importlib_resources-5.6.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/attrs-21.4.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_core-4.9.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jsonschema-4.4.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/pyzmq-22.3.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/nest_asyncio-1.5.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/entrypoints-0.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pyparsing-3.0.7-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pycparser-2.21-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbformat-5.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_client-7.2.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/webencodings-0.5.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/packaging-21.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/soupsieve-2.3.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/pure_eval-0.2.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/executing-0.8.3-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/asttokens-2.0.5-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/wcwidth-0.2.5-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ptyprocess-0.7.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/parso-0.8.3-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/testpath-0.6.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pandocfilters-1.5.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbclient-0.5.13-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/mistune-0.8.4-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_pygments-0.1.2-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Jinja2-3.1.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/bleach-4.1.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/beautifulsoup4-4.10.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/sniffio-1.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/stack_data-0.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/setuptools-61.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/prompt_toolkit-3.0.28-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pickleshare-0.7.5-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pexpect-4.8.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/matplotlib_inline-0.1.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jedi-0.18.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/decorator-5.1.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/backcall-0.2.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/websocket_client-1.3.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/terminado-0.13.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Send2Trash-1.8.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/prometheus_client-0.13.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbconvert-6.4.5-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/argon2_cffi-21.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/anyio-3.5.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/psutil-5.9.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/ipython-8.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/debugpy-1.6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server-1.16.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipython_genutils-0.2.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipykernel-6.11.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/notebook_shim-0.1.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/notebook-6.4.10-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/json5-0.9.6-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Babel-2.9.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbclassic-0.3.7-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_server-2.12.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/QtPy-2.0.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/widgetsnbextension-3.6.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_widgets-1.1.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab-3.3.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/qtconsole-5.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_console-6.4.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipywidgets-7.7.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/lckr_jupyterlab_variableinspector-3.0.9.tar.gz
pip3 install --no-dependencies /tmp/packages/jupyter-1.0.0-py2.py3-none-any.whl
