R CMD INSTALL --build \
/tmp/packages/rlang_1.0.2.tar.gz \
/tmp/packages/fastmap_1.1.0.tar.gz \
/tmp/packages/fansi_1.0.3.tar.gz \
/tmp/packages/glue_1.6.2.tar.gz \
/tmp/packages/utf8_1.2.2.tar.gz \
/tmp/packages/base64enc_0.1-3.tar.gz \
/tmp/packages/evaluate_0.15.tar.gz \
/tmp/packages/pbdZMQ_0.3-7.tar.gz \
/tmp/packages/crayon_1.5.1.tar.gz \
/tmp/packages/jsonlite_1.8.0.tar.gz \
/tmp/packages/uuid_1.0-4.tar.gz \
/tmp/packages/digest_0.6.29.tar.gz \
/tmp/packages/cli_3.2.0.tar.gz \
/tmp/packages/ellipsis_0.3.2.tar.gz \
/tmp/packages/lifecycle_1.0.1.tar.gz \
/tmp/packages/htmltools_0.5.2.tar.gz \
/tmp/packages/vctrs_0.4.0.tar.gz \
/tmp/packages/pillar_1.7.0.tar.gz \
/tmp/packages/repr_1.1.4.tar.gz \
/tmp/packages/IRdisplay_1.1.tar.gz \
/tmp/packages/IRkernel_1.3.tar.gz \
